# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axf', '0006_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=32)),
                ('productimg', models.CharField(max_length=200)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=200)),
                ('isxf', models.BooleanField(default=False)),
                ('pmdesc', models.CharField(max_length=100)),
                ('specifics', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('marketprice', models.CharField(max_length=100)),
                ('categoryid', models.CharField(max_length=100)),
                ('childcid', models.CharField(max_length=100)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=100)),
                ('storenums', models.CharField(max_length=100)),
                ('productnum', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
