# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    #初始化=True
    initial = True
    # 依赖
    dependencies = [
    ]
    # 操作
    operations = [
        # 创建模型
        migrations.CreateModel(
            name='Grade',
            # 域
            fields=[
                # 主键primary_key,关系型数据库必须有主键。
                #                 自动场      自动创建             主键            连载             详细名称
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='Python709', max_length=16)),
                ('g_boy_num', models.IntegerField(default=0)),
                ('g_girl_num', models.IntegerField(default=0)),
            ],
        ),
    ]
