# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('trackid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MainNav',
            fields=[
                ('basemain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.BaseMain')),
            ],
            options={
                'db_table': 'axf_nav',
            },
            bases=('App.basemain',),
        ),
        migrations.CreateModel(
            name='MainWheel',
            fields=[
                ('basemain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.BaseMain')),
            ],
            options={
                'db_table': 'axf_wheel',
            },
            bases=('App.basemain',),
        ),
    ]
